version: '3.7'

services:

  fronttest:
    container_name: FrontTest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4444:44486
    environment:
      - CHOKIDAR_USEPOLLING=true
